### ISSUE TITLE
Enoncé 1

### ISSUE THREAD

**Issue by umeima** [umeima/workshop-js#2]
- [ ] réaliser le Énonce 1 en parallèle avec documentation

**Comment by umeima** [comment]
Enonce 1 done

**Comment by youssefbm** [comment]
Hello umeima, essayer de revoir votre solution. Consultez Khadija Ezzayani, j'ai jeté un coup d'oeil sur sa sollution et je pense qu'il est correcte.

**Comment by youssefbm** [comment]
Keep going umeima
